//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    using ViewModel;

    public partial class InputInfo:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InputInfo()
        {
            this.OutputInfoes = new HashSet<OutputInfo>();
        }
    
        public string Id { get; set; }
        private string _IdObject ;
        private string _IdInput ;
        private Nullable<int> _Count ;
        private Nullable<double> _InputPrice ;
        private Nullable<double> _OutputPrice ;
        private string _Status ;
    
        private  Input _Input ;
        private  Object _Object ;
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutputInfo> OutputInfoes { get; set; }

        public string IdObject
        {
            get
            {
                return _IdObject;
            }

            set
            {
                _IdObject = value;
                OnPropertyChanged();
                
            }
        }

        public string IdInput
        {
            get
            {
                return _IdInput;
            }

            set
            {
                _IdInput = value;
                OnPropertyChanged();

            }
        }

        public int? Count
        {
            get
            {
                return _Count;
            }

            set
            {
                _Count = value;
                OnPropertyChanged();

            }
        }

        public double? InputPrice
        {
            get
            {
                return _InputPrice;
            }

            set
            {
                _InputPrice = value;
                OnPropertyChanged();

            }
        }

        public double? OutputPrice
        {
            get
            {
                return _OutputPrice;
            }

            set
            {
                _OutputPrice = value;
                OnPropertyChanged();

            }
        }

        public string Status
        {
            get
            {
                return _Status;
            }

            set
            {
                _Status = value;
                OnPropertyChanged();

            }
        }

        public virtual Input Input
        {
            get
            {
                return _Input;
            }

            set
            {
                _Input = value;
                OnPropertyChanged();

            }
        }

        public virtual Object Object
        {
            get
            {
                return _Object;
            }

            set
            {
                _Object = value;
                OnPropertyChanged();

            }
        }
    }
}
