//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    using ViewModel;

    public partial class Object:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object()
        {
            this.InputInfoes = new HashSet<InputInfo>();
            this.OutputInfoes = new HashSet<OutputInfo>();
        }
    
        public string Id { get; set; }
        private string _DisplayName ;
        private int _IdUnit ;
        private int _IdSuplier ;
        private string _QRCode ;
        private string _BarCode ;
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InputInfo> InputInfoes { get; set; }
        private  Unit _Unit ;
        private  Suplier _Suplier ;
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutputInfo> OutputInfoes { get; set; }

        public string DisplayName
        {
            get
            {
                return _DisplayName;
            }

            set
            {
                _DisplayName = value;
                OnPropertyChanged();
                
            }
        }

        public int IdUnit
        {
            get
            {
                return _IdUnit;
            }

            set
            {
                _IdUnit = value;
                OnPropertyChanged();
            }
        }

        public int IdSuplier
        {
            get
            {
                return _IdSuplier;
            }

            set
            {
                _IdSuplier = value;
                OnPropertyChanged();
            }
        }

        public string QRCode
        {
            get
            {
                return _QRCode;
            }

            set
            {
                _QRCode = value;
                OnPropertyChanged();

            }
        }

        public string BarCode
        {
            get
            {
                return _BarCode;
            }

            set
            {
                _BarCode = value;
                OnPropertyChanged();

            }
        }

        public Unit Unit
        {
            get
            {
                return _Unit;
            }

            set
            {
                _Unit = value;
                OnPropertyChanged();

            }
        }

        public Suplier Suplier
        {
            get
            {
                return _Suplier;
            }

            set
            {
                _Suplier = value;
                OnPropertyChanged();

            }
        }
    }
}
