//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    using ViewModel;

    public partial class User:BaseViewModel
    {
        public int Id { get; set; }

        public string DisplayName
        {
            get
            {
                return _DisplayName;
            }

            set
            {
                _DisplayName = value;
                OnPropertyChanged();
            }
        }

        public string UserName
        {
            get
            {
                return _UserName;
            }

            set
            {
                _UserName = value;
                OnPropertyChanged();
            }
        }

        public string Password
        {
            get
            {
                return _Password;
            }

            set
            {
                _Password = value;
                OnPropertyChanged();
            }
        }

        public int IdRole
        {
            get
            {
                return _IdRole;
            }

            set
            {
                
                _IdRole = value;
                OnPropertyChanged();
            }
        }

        public virtual UserRole UserRole
        {
            get
            {
                return _UserRole;
            }

            set
            {
                _UserRole = value;
                OnPropertyChanged();
            }
        }

        private string _DisplayName ;
        private string _UserName ;
        private string _Password ;
        private int _IdRole ;

        private  UserRole _UserRole;
    }
}
